### ISSUE TITLE
checkpoint data unable to be saved

### ISSUE THREAD

**Issue by shiba-san** [brainhack-dsta/til-ai-camp#1]
from keras.models import load_model

model_path = 'saved_model.hdf5'
model = load_model( model_path )

when run gets OSError                                   Traceback (most recent call last)
<ipython-input-12-872a231dcd82> in <module>()
      2 
      3 model_path = 'saved_model.hdf5'
----> 4 model = load_model( model_path )

3 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    140         if swmr and swmr_support:
    141             flags |= h5f.ACC_SWMR_READ
--> 142         fid = h5f.open(name, flags, fapl=fapl)
    143     elif mode == 'r+':
    144         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'saved_model.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by DerekChia** [comment]
Did you make sure that you have the file `saved_model.hdf5` saved in the same directory as your jupyter notebook?
